id = "acaibird-material-icon-theme"
name = "VSCode Material Icon Theme"
version = "0.1.2"
schema_version = 1
authors = ["Acaibird"]
description = "Material Design icons."
repository = "https://github.com/A-caibird/material-icon-theme#"
